version: 2
updates:
  - package-ecosystem: npm
    directory: /
    schedule:
      interval: monthly
    labels: [dependencies]
    ignore:
      - dependency-name: html-validate
        update-types: [version-update:semver-major]
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: monthly
    labels: [dependencies]
  - package-ecosystem: docker
    directory: /
    schedule:
      interval: monthly
    labels: [dependencies]
