services:
  ultimate-animation-index:
    build: .
    ports:
      - '8787:8787'
    environment:
      PORT: 8787
    volumes:
      - ./.userlist-keys:/app/.userlist-keys
      - ./.cache:/app/.cache
      - ./covers:/app/covers
    restart: unless-stopped
